project:
  type: website
  output-dir: docs

website:
  title: "tsa-lecture-notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: TSA-Lecture01.qmd
        text: Lecture 1

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



