project:
  type: website
  output-dir: docs

website:
  title: "tsa-lecture-notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: TSA-Lecture01.qmd
        text: Lecture 1
      - href: TSA-Lecture02.qmd
        text: Lecture 2
      - href: TSA-Lecture03.qmd
        text: Lecture 3
      - href: TSA-Lecture04.qmd
        text: Lecture 4
      - href: TSA-Lecture05.qmd
        text: Lecture 5
      - href: TSA-Lecture06.qmd
        text: Lecture 6
      - href: TSA-Lecture07.qmd
        text: Lecture 7
      - href: TSA-Lecture07-plots.qmd
        text: "Rnotebook: Visualizing Time Series"
      - href: TSA-Lecture08.qmd
        text: Lecture 8
      - href: TSA-Lecture08-regression-methods.qmd
        text: "Rnotebook: Regression"
      - href: TSA-Lecture09.qmd
        text: Lecture 9
      - href: TSA-Lecture09.qmd
        text: Lecture 10
      - href: TSA-Lecture09.qmd
        text: Lecture 11
      - href: TSA-Lecture09.qmd
        text: Lecture 12
      - href: TSA-Lecture09.qmd
        text: Lecture 13
      - href: TSA-Lecture09.qmd
        text: Lecture 14
      - href: TSA-Lecture09.qmd
        text: Lecture 15
      - href: TSA-Lecture09.qmd
        text: Lecture 16
      - href: TSA-Lecture09.qmd
        text: Lecture 17
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-navigation: true



