project:
  type: website

website:
  title: "Lecture Notes"
  sidebar:
    # optional: set width in pixels
    width: 250px
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: TSA-Lecture01.qmd
        text: Lecture 1
      - href: TSA-Lecture02.qmd
        text: Lecture 2
      - href: TSA-Lecture03.qmd
        text: Lecture 3
      - href: TSA-Lecture04.qmd
        text: Lecture 4
      - href: TSA-Lecture05.qmd
        text: Lecture 5
      - href: TSA-Lecture06.qmd
        text: Lecture 6
      - href: TSA-Lecture07.qmd
        text: Lecture 7
          - href: TSA-Lecture07-plots.qmd
            text: "R notebook: Plots"
      - href: TSA-Lecture08.qmd
        text: Lecture 8
        - href: TSA-Lecture08-regression-methods.qmd
          text: "R notebook: Regression Methods"
      - href: TSA-Lecture09.qmd
        text: Lecture 9
      - href: TSA-Lecture10.qmd
        text: Lecture 10
      - href: TSA-Lecture11.qmd
        text: Lecture 11
      - href: TSA-Lecture12.qmd
        text: Lecture 12
      - href: TSA-Lecture13.qmd
        text: Lecture 13
      - href: TSA-Lecture14.qmd
        text: Lecture 14
        - href: TSA-Lecture14-model-specification.qmd
          text: "R notebook: Model Specification"
      - href: TSA-Lecture15.qmd
        text: Lecture 15
      - href: TSA-Lecture16.qmd
        text: Lecture 16
          - href: TSA-Lecture16-parameter-estimation.qmd
            text: "R notebook: Parameter Estimation"
      - href: TSA-Lecture17.qmd
        text: Lecture 17
          - href: TSA-Lecture17-model-diagnostics.qmd
            text: "R notebook: Diagnostics"
      - href: TSA-Lecture18.qmd
        text: Lecture 18
      - href: TSA-Lecture19.qmd
        text: Lecture 19
          - href: TSA-Lecture19-forecasting.qmd
            text: "R notebook: Forecasting"
      - href: TSA-Lecture20.qmd
        text: Lecture 20
          - href: TSA-Lecture20-sarima.qmd
            text: "R notebook: SARIMA"
      - href: TSA-Lecture21.qmd
        text: Lecture 21
      - href: TSA-Lecture22.qmd
        text: Lecture 22
          - href: TSA-Lecture22-spurious.qmd
            text: "R notebook: Advanced Topics"
      - href: TSA-Lecture23.qmd
        text: Lecture 23
          - href: TSA-Lecture23-arch-garch.qmd
            text: "R notebook: Advanced Topics"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-navigation: true



