project:
  type: website

website:
  title: "Lecture Notes"
  sidebar:
    # optional: set width in pixels
    width: 250px
    contents:
      - href: index.qmd
        text: Home
      - text: Courses
        menu:
          - text: Time Series Analysis
            href: tsa/index.qmd
          - text: Bayesian Statistics
            href: bayes/index.qmd
          - text: Applied Statistics and Data Analysis I
            href: asda1/index.qmd
          - text: Applied Statistics and Data Analysis II
            href: asda2/index.qmd
          - text: Elements of Statistical Learning
            href: esl/index.qmd
      - href: about.qmd
        text: About
      
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-navigation: true



