project:
  type: website
  output-dir: docs

website:
  title: "tsa-lecture-notes"
  sidebar:
    # optional: set width in pixels
    width: 250px
    contents:
      - href: index.qmd
        text: Home
      - href: TSA-Lecture01.qmd
        text: Lecture 1
      - href: TSA-Lecture02.qmd
        text: Lecture 2
      - href: TSA-Lecture03.qmd
        text: Lecture 3
      - href: TSA-Lecture04.qmd
        text: Lecture 4
      - href: TSA-Lecture05.qmd
        text: Lecture 5
      - href: TSA-Lecture06.qmd
        text: Lecture 6
      - href: TSA-Lecture07.qmd
        text: Lecture 7
      - href: TSA-Lecture07-plots.qmd
        text: "Rnotebook: Visualizing Time Series"
      - href: TSA-Lecture08.qmd
        text: Lecture 8
      - href: TSA-Lecture08-regression-methods.qmd
        text: "Rnotebook: Regression"
      - href: TSA-Lecture09.qmd
        text: Lecture 9
      - href: TSA-Lecture14-model-specification.qmd
        text: "Rnotebook: Model Specification"
      - href: TSA-Lecture16-parameter-estimation.qmd
        text: "Rnotebook: Parameter Estimation"
      - href: TSA-Lecture17-model-diagnostics.qmd
        text: "Rnotebook: Model Diagnostics"
      - href: TSA-Lecture19-forecasting.qmd
        text: "Rnotebook: Forecasting"
      - href: TSA-Lecture20-sarima.qmd
        text: "Rnotebook: SARIMA"
      - href: TSA-Lecture22-spurious.qmd
        text: "Rnotebook: Spurious Regression"
      - href: TSA-Lecture23.qmd
      - text: Lecture 23
      - href: TSA-Lecture23-arch-garch.qmd
        text: "Rnotebook: ARCH/GARCH"
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-navigation: true



