{
  "hash": "22a0b270f15a1f50ae15b00c1299566d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"439/639 TSA: Parameter Estimation\"\nauthor: \"Dr Sergey Kushnarev\"\nformat:\n  html:\n    toc: true\n    number-sections: true\n    code-fold: true\n---\n\n\n\n\n\n \n## Steps in Time Series Analysis            \n\n|   |   |   |   |\n|:---:|:---:|:---:|:---:|\n| Step 1: Model Specification |  **Step 2: Parameter Estimation**  | Step 3: Model Checking | Step 4: Forecasting |\n\n\n\n\n\n# Parameter Estimation\n\nThis R Notebook is based on Chapter 7, Cryer and Chan. We illustrate the following methods of parameters estimation for ARMA models:\n\n- Method of Moments (Yule-Walker method), \n- Conditional Least Squares, \n- Maximum Likelihood Estimation, \n- Unconditional Least Squares. \n\nWe assume that $p,d,q$ are known and we are interested in estimating the parameters of the model. \n\nAssume $Y_1,Y_2,\\ldots,Y_n$ is an observed **stationary** time series, or a corresponding difference of the original series. \n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(TSA)\n```\n:::\n\n\n\n\n## Method of Moments\n\n### MA(1)\n\nThe method of moments estimator of the MA(1) coefficient $\\theta$ is given by the solution of the following quadratic equation:\n$$\nr_1\\theta^2 + \\theta  + r_1 = 0,\n$$\nwhere $r_1$ is the sample lag 1 ACF of the time series.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Below is a function that computes the method of moments estimator of\n# the MA(1) coefficient of an MA(1) model.\nestimate.ma1.mom = function(x){\n    r=acf(x,plot=F)$acf[1] \n    if (abs(r)<0.5) \n        return((-1+sqrt(1-4*r^2))/(2*r)) \n    else \n        return(NA)\n        }\n\n# Exhibit 7.1\ndata(ma1.2.s)\nestimate.ma1.mom(ma1.2.s)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.5554273\n```\n\n\n:::\n\n```{.r .cell-code}\ndata(ma1.1.s)\nestimate.ma1.mom(ma1.1.s)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7196756\n```\n\n\n:::\n\n```{.r .cell-code}\nset.seed(1234)\nma1.3.s=arima.sim(list(ma=c(-0.9)),n=60)\nestimate.ma1.mom(ma1.3.s)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] NA\n```\n\n\n:::\n\n```{.r .cell-code}\nma1.4.s=arima.sim(list(ma=c(-0.5)),n=60) \nestimate.ma1.mom(ma1.4.s)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2571377\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Display the results of the method of moments for all MA(1) models above in a table format\nlibrary(knitr)\nkable(data.frame(\n    c('ma1.1.s','ma1.2.s','ma1.3.s','ma1.4.s'),\n    c(0.9,-0.9,0.9,0.5),\n    c(estimate.ma1.mom(ma1.1.s),estimate.ma1.mom(ma1.2.s),\n      estimate.ma1.mom(ma1.3.s),estimate.ma1.mom(ma1.4.s)),\n    c(120,120,60,60)),\n    col.names=c('Data','True Value theta','Estimate of MA(1)', 'Sample size')\n    )  \n```\n\n::: {.cell-output-display}\n\n\n|Data    | True Value theta| Estimate of MA(1)| Sample size|\n|:-------|----------------:|-----------------:|-----------:|\n|ma1.1.s |              0.9|         0.7196756|         120|\n|ma1.2.s |             -0.9|        -0.5554273|         120|\n|ma1.3.s |              0.9|                NA|          60|\n|ma1.4.s |              0.5|         0.2571377|          60|\n\n\n:::\n:::\n\n\n\n\n### AR(p)\n\nMethod of moments estimator of the AR(1) coefficient $\\phi$ is given by\n$$\n\\widehat\\phi_{MoM}=r_1.\n$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fitting an AR(1) model to the data\ndata(ar1.s)\nar(ar1.s,order.max=1,AIC=F,method='yw')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nar(x = ar1.s, order.max = 1, method = \"yw\", AIC = F)\n\nCoefficients:\n     1  \n0.8314  \n\nOrder selected 1  sigma^2 estimated as  1.382\n```\n\n\n:::\n\n```{.r .cell-code}\ndata(ar1.2.s)\nar(ar1.2.s,order.max=1,AIC=F,method='yw')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nar(x = ar1.2.s, order.max = 1, method = \"yw\", AIC = F)\n\nCoefficients:\n     1  \n0.4699  \n\nOrder selected 1  sigma^2 estimated as  0.9198\n```\n\n\n:::\n\n```{.r .cell-code}\ndata(ar2.s)\nar(ar2.s,order.max=2,AIC=F,method='yw')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nar(x = ar2.s, order.max = 2, method = \"yw\", AIC = F)\n\nCoefficients:\n      1        2  \n 1.4694  -0.7646  \n\nOrder selected 2  sigma^2 estimated as  1.051\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Display the results of the method of moments for all AR(1) models above in a table format\nkable(data.frame(\n    c('ar1.s','ar1.2.s','ar2.s','--'),\n    c('0.9','0.4','1.5','-0.75'),\n    c(ar(ar1.s,order.max=1,AIC=F,method='yw')$ar, \n      ar(ar1.2.s,order.max=1,AIC=F,method='yw')$ar,\n      ar(ar2.s,order.max=2,AIC=F,method='yw')$ar),\n    c(120,120,120, '--')),\n    col.names=c('Data','True Value phi','Estimate of AR(1)', 'Sample size')\n    )\n```\n\n::: {.cell-output-display}\n\n\n|Data    |True Value phi | Estimate of AR(1)|Sample size |\n|:-------|:--------------|-----------------:|:-----------|\n|ar1.s   |0.9            |         0.8313820|120         |\n|ar1.2.s |0.4            |         0.4699186|120         |\n|ar2.s   |1.5            |         1.4694476|120         |\n|--      |-0.75          |        -0.7646034|--          |\n\n\n:::\n:::\n\n\n\n\n## Comparison of Estimation methods\n\nWe will compare Method of Moments, Conditional Sum of Squares, and Maximum Likelihood Methods\n\n### AR(1)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Exhibit 7.4\ndata(ar1.s)\nar(ar1.s,order.max=1,AIC=F,method='yw') # method of moments\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nar(x = ar1.s, order.max = 1, method = \"yw\", AIC = F)\n\nCoefficients:\n     1  \n0.8314  \n\nOrder selected 1  sigma^2 estimated as  1.382\n```\n\n\n:::\n\n```{.r .cell-code}\nar(ar1.s,order.max=1,AIC=F,method='ols') # conditional sum of squares\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nar(x = ar1.s, order.max = 1, method = \"ols\", AIC = F)\n\nCoefficients:\n    1  \n0.857  \n\nIntercept: 0.02499 (0.1308) \n\nOrder selected 1  sigma^2 estimated as  1.008\n```\n\n\n:::\n\n```{.r .cell-code}\nar(ar1.s,order.max=1,AIC=F,method='mle') # maximum likelihood\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nar(x = ar1.s, order.max = 1, method = \"mle\", AIC = F)\n\nCoefficients:\n     1  \n0.8924  \n\nOrder selected 1  sigma^2 estimated as  1.041\n```\n\n\n:::\n\n```{.r .cell-code}\n# The AIC option is set to be False otherwise the function will choose\n# the AR order by minimizing AIC, so that zero order might be chosen.\n\ndata(ar1.2.s)\nar(ar1.2.s,order.max=1,AIC=F,method='yw') # method of moments\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nar(x = ar1.2.s, order.max = 1, method = \"yw\", AIC = F)\n\nCoefficients:\n     1  \n0.4699  \n\nOrder selected 1  sigma^2 estimated as  0.9198\n```\n\n\n:::\n\n```{.r .cell-code}\nar(ar1.2.s,order.max=1,AIC=F,method='ols') # conditional sum of squares\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nar(x = ar1.2.s, order.max = 1, method = \"ols\", AIC = F)\n\nCoefficients:\n     1  \n0.4731  \n\nIntercept: -0.006084 (0.1237) \n\nOrder selected 1  sigma^2 estimated as  0.9024\n```\n\n\n:::\n\n```{.r .cell-code}\nar(ar1.2.s,order.max=1,AIC=F,method='mle') # maximum likelihood\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nar(x = ar1.2.s, order.max = 1, method = \"mle\", AIC = F)\n\nCoefficients:\n     1  \n0.4654  \n\nOrder selected 1  sigma^2 estimated as  0.8875\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Display the results of the method of moments, conditional sum of squares, and maximum likelihood for AR(1) models above in a table format\nkable(data.frame(\n    c('ar1.s','ar1.2.s'),\n    c('0.9','0.4'),\n    c(ar(ar1.s,order.max=1,AIC=F,method='yw')$ar, \n      ar(ar1.2.s,order.max=1,AIC=F,method='yw')$ar),\n    c(ar(ar1.s,order.max=1,AIC=F,method='ols')$ar, \n      ar(ar1.2.s,order.max=1,AIC=F,method='ols')$ar),\n    c(ar(ar1.s,order.max=1,AIC=F,method='mle')$ar, \n      ar(ar1.2.s,order.max=1,AIC=F,method='mle')$ar),\n    c(60,60)),\n    col.names=c('Data','True Value phi','MoM of AR(1)', 'CSS of of AR(1)', 'MLE of AR(1)', 'Sample size')\n    )\n```\n\n::: {.cell-output-display}\n\n\n|Data    |True Value phi | MoM of AR(1)| CSS of of AR(1)| MLE of AR(1)| Sample size|\n|:-------|:--------------|------------:|---------------:|------------:|-----------:|\n|ar1.s   |0.9            |    0.8313820|       0.8570411|    0.8923649|          60|\n|ar1.2.s |0.4            |    0.4699186|       0.4730960|    0.4653505|          60|\n\n\n:::\n:::\n\n\n\n\nThe standard errors of the estimated AR(1) coefficients are given by the following formula:\n$$\nSE(\\hat\\phi)=\\sqrt{\\widehat{\\text{Var}}(\\hat\\phi)}=\\frac{1-\\hat\\phi^2}{n}\n$$\n\nFor example, for the first AR(1) model, we have $\\hat\\phi=0.89$ and $n=60$, so that $SE(\\hat\\phi)=\\approx 0.06$.\n\nAnd for the second AR(1) model, we have $\\hat\\phi=0.465$ and $n=60$, so that $SE(\\hat\\phi)=\\approx 0.11$.\n\nAll the estimates are comparable.\n\n### AR(2)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Exhibit 7.5\ndata(ar2.s)\nar(ar2.s,order.max=2,AIC=F,method='yw') # method of moments\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nar(x = ar2.s, order.max = 2, method = \"yw\", AIC = F)\n\nCoefficients:\n      1        2  \n 1.4694  -0.7646  \n\nOrder selected 2  sigma^2 estimated as  1.051\n```\n\n\n:::\n\n```{.r .cell-code}\nar(ar2.s,order.max=2,AIC=F,method='ols') # conditional sum of squares\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nar(x = ar2.s, order.max = 2, method = \"ols\", AIC = F)\n\nCoefficients:\n      1        2  \n 1.5137  -0.8050  \n\nIntercept: 0.02043 (0.08594) \n\nOrder selected 2  sigma^2 estimated as  0.8713\n```\n\n\n:::\n\n```{.r .cell-code}\nar(ar2.s,order.max=2,AIC=F,method='mle') # maximum likelihood\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nar(x = ar2.s, order.max = 2, method = \"mle\", AIC = F)\n\nCoefficients:\n      1        2  \n 1.5061  -0.7964  \n\nOrder selected 2  sigma^2 estimated as  0.862\n```\n\n\n:::\n\n```{.r .cell-code}\n# Display the results of the method of moments, conditional sum of squares, and maximum likelihood for AR(2) models above in a table format\nkable(data.frame(\n    c('ar2.s'),\n    c('1.5','-0.75'),\n    c(ar(ar2.s,order.max=2,AIC=F,method='yw')$ar),\n    c(ar(ar2.s,order.max=2,AIC=F,method='ols')$ar),\n    c(ar(ar2.s,order.max=2,AIC=F,method='mle')$ar),\n    c(120)),\n    col.names=c('Data','True Value phi_i','MoM of AR(2)', 'CSS of AR(2)', 'MLE of AR(2)', 'Sample size')\n    )\n```\n\n::: {.cell-output-display}\n\n\n|Data  |True Value phi_i | MoM of AR(2)| CSS of AR(2)| MLE of AR(2)| Sample size|\n|:-----|:----------------|------------:|------------:|------------:|-----------:|\n|ar2.s |1.5              |    1.4694476|    1.5137146|    1.5061369|         120|\n|ar2.s |-0.75            |   -0.7646034|   -0.8049905|   -0.7964453|         120|\n\n\n:::\n:::\n\n\n\n\nStandard errors of the estimated AR(2) coefficients are given by the following formula:\n\n$$\nSE(\\hat\\phi_1)\\approx SE(\\hat\\phi_2)\\approx\\sqrt{\\frac{1-\\hat\\phi_2^2}{n}}\\approx 0.06\n$$\n\n\n\n## Conditional Least Squares/Sum of Squares\n\n### MA(1)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using conditinal sum of squares method\narima(ma1.4.s,order=c(0,0,1),method='CSS',include.mean=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\narima(x = ma1.4.s, order = c(0, 0, 1), include.mean = F, method = \"CSS\")\n\nCoefficients:\n         ma1\n      -0.474\ns.e.   0.191\n\nsigma^2 estimated as 0.7329:  part log likelihood = -75.81\n```\n\n\n:::\n:::\n\n\n\n\n### ARMA(1,1)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fitting an ARMA(1,1) model to the data\n# Exhibit 7.6\ndata(arma11.s)\narima(arma11.s, order=c(1,0,1),method='CSS') # conditional sum of squares\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\narima(x = arma11.s, order = c(1, 0, 1), method = \"CSS\")\n\nCoefficients:\n         ar1     ma1  intercept\n      0.5586  0.3669     0.3928\ns.e.  0.1219  0.1564     0.3380\n\nsigma^2 estimated as 1.199:  part log likelihood = -150.98\n```\n\n\n:::\n\n```{.r .cell-code}\narima(arma11.s, order=c(1,0,1),method='ML') # maximum likelihood\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\narima(x = arma11.s, order = c(1, 0, 1), method = \"ML\")\n\nCoefficients:\n         ar1     ma1  intercept\n      0.5647  0.3557     0.3216\ns.e.  0.1205  0.1585     0.3358\n\nsigma^2 estimated as 1.197:  log likelihood = -151.33,  aic = 308.65\n```\n\n\n:::\n\n```{.r .cell-code}\n# \n# Recall that R uses the plus convention whereas our book uses the minus \n# convention in the specification of the MA part, i.e. R specifies an\n# ARMA(1,1) model as z_t=theta_0+phi*z_{t-1}+e_t+theta_1*e_{t-1} \n# versus our convention\n# z_t=theta_0+phi*z_{t-1}+e_t-theta_1*e_{t-1} \n```\n:::\n\n\n\n\n| Parameter | MOM | CSS | UCSS | MLE | $n$   |\n|-----------|-------------------|----------------|-------------------|---------------------|-----|\n| $\\phi = 0.6$   | 0.637             | 0.5586         | 0.5691            | 0.5647              | 100 |\n| $\\theta = −0.3$  | −0.2066           | −0.3669        | −0.3618           | −0.3557             | 100 |\n\n\n\\newpage\n\n# Parameter Estimation for Some Actual Time Series\n\n### Color Property\n\nThe sample PACF of the color property dataset strongly suggested an AR(1) model. We will fit an AR(1) model to the color property dataset using the method of moments, conditional sum of squares, and maximum likelihood methods.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Exhibit 7.7\ndata(color)\nar(color,order.max=1,AIC=F,method='yw') # method of moments\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nar(x = color, order.max = 1, method = \"yw\", AIC = F)\n\nCoefficients:\n     1  \n0.5282  \n\nOrder selected 1  sigma^2 estimated as  27.56\n```\n\n\n:::\n\n```{.r .cell-code}\nar(color,order.max=1,AIC=F,method='ols') # conditional sum of squares\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nar(x = color, order.max = 1, method = \"ols\", AIC = F)\n\nCoefficients:\n     1  \n0.5549  \n\nIntercept: 0.1032 (0.8474) \n\nOrder selected 1  sigma^2 estimated as  24.38\n```\n\n\n:::\n\n```{.r .cell-code}\nar(color,order.max=1,AIC=F,method='mle') # maximum likelihood\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nar(x = color, order.max = 1, method = \"mle\", AIC = F)\n\nCoefficients:\n     1  \n0.5703  \n\nOrder selected 1  sigma^2 estimated as  24.83\n```\n\n\n:::\n:::\n\n\n\n\n| Parameter | MoM | CSS  | Unconditional SS | MLE | $n$  |\n|-----------|-----------------------------|--------------------------|----------------------------|------------------------------|----|\n| $\\phi$         | 0.5282                      | 0.5549                   | 0.5890                     | 0.5703                       | 35 |\n\nThe standard error of the estimated AR(1) coefficient is given by the following formula:\n$$\nSE(\\hat\\phi)=\\sqrt{\\widehat{\\text{Var}}(\\hat\\phi)}=\\sqrt{\\frac{1-\\hat\\phi^2}{n}}\\approx 0.14\n$$\n\nAll estimates are comparable. \n\n### Hare Data\n\nWe are fitting an AR(3) model to the square root of the hare data, $\\sqrt{Y_t}$.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Exhibit 7.8\ndata(hare)\narima(sqrt(hare),order=c(3,0,0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\narima(x = sqrt(hare), order = c(3, 0, 0))\n\nCoefficients:\n         ar1      ar2      ar3  intercept\n      1.0519  -0.2292  -0.3931     5.6923\ns.e.  0.1877   0.2942   0.1915     0.3371\n\nsigma^2 estimated as 1.066:  log likelihood = -46.54,  aic = 101.08\n```\n\n\n:::\n:::\n\n\n\n\n| Coefficient | Estimate | Std. Error |\n|-------------|----------|------------|\n| $\\phi_1$         | $\\phantom{-}1.0519$   | 0.1877     |\n| $\\phi_2$    | $−0.2292$  | 0.2942     |\n| $\\phi_3$    | $−0.3931$  | 0.1915     |\n| Intercept*  | $\\phantom{-}5.6923$   | 0.3371     |\n\n* The intercept here is the estimate of the process mean $\\mu$.\n\n- $\\sigma^2$ estimated as 1.066  \n- Log-likelihood = −46.54  \n- AIC = 101.08\n\nThe fitted model is:\n\n\\begin{align*}\n\\sqrt{Y_t} - 5.6923 &= 1.0519(\\sqrt{Y_{t-1}} - 5.6923) - 0.2292(\\sqrt{Y_{t-2}} - 5.6923) \\\\\n&\\quad - 0.3930(\\sqrt{Y_{t-3}} - 5.6923) + e_t \\\\\n\\sqrt{Y_t} &= 3.25 + 1.0519\\, \\sqrt{Y_{t-1}} - 0.2292\\, \\sqrt{Y_{t-2}} - 0.3930\\, \\sqrt{Y_{t-3}} + e_t\n\\end{align*}\n\nNotice, $\\phi_2$ is not significantly different from 0, so we can drop it from the model and refit the AR(3) model with only $\\phi_1$ and $\\phi_3$ coefficients.\n\n### Oil-prices\n\nWe are fitting the ARIMA(0,1,1) model to the log of oil prices, $\\log(Y_t)$, or an ARMA(0,1)=MA(1) model to the first differences of the log of oil prices, $\\nabla\\log Y_t$:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Exhibit 7.9\ndata(oil.price)\narima(log(oil.price),order=c(0,1,1),method='CSS') # conditional sum of squares\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\narima(x = log(oil.price), order = c(0, 1, 1), method = \"CSS\")\n\nCoefficients:\n         ma1\n      0.2731\ns.e.  0.0681\n\nsigma^2 estimated as 0.006731:  part log likelihood = 259.58\n```\n\n\n:::\n\n```{.r .cell-code}\narima(log(oil.price),order=c(0,1,1),method='ML') # maximum likelihood\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\narima(x = log(oil.price), order = c(0, 1, 1), method = \"ML\")\n\nCoefficients:\n         ma1\n      0.2956\ns.e.  0.0693\n\nsigma^2 estimated as 0.006689:  log likelihood = 260.29,  aic = -518.58\n```\n\n\n:::\n:::\n\n\n\n\n| Parameter | MoM | CSS | UCSS  | MLE | $n$   |\n|-----------|-----------------------------|--------------------------|----------------------------|------------------------------|-----|\n| $\\theta$         | $−0.2225$                     | $−0.2731$                  | $−0.2954$                   | $−0.2956$                      | 241 |\n\n\nAll estimates are comparable, since the standard errors are close to 0.06. \n\n**Exercise** Find the standard error of the estimated MA(1) coefficient $\\theta$.\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}